server:
  host: 127.0.0.1
  port: 4001
  mode: debug
redis:
  host: "127.0.0.1"
  port: "6379"
  password: ""
  database: 9
  pool:
    pool-size: 200
    min-idle: 50
database:
  host: 127.0.0.1
  port: 3306
  database: orca
  username: root
  password: 123456
  pool:
    max-open-connection: 100
    max-idle-connection: 10
    idle-timeout: 30000
    max-lifetime: 60000
kubernetes:
  host:
  port:
security:
  password-encrypt: false
  encrypt-key: ""
  multi-login: false
  login-attempt:
    enable: true
    times-before-lock: 5
    locking-duration: 1800